<a href="https://colab.research.google.com/github/finesun16/netology_pyda_27_hw/blob/master/hw_4_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

In [40]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

In [41]:
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`


In [8]:
# если просто поиск документа
while True:
    order = input('Введите команду: \n').lower()
    if order == 'q':
        print('Всего хорошего')
        break
    elif order == 'p':
        num_doc = input('Введите номер документа: \n')
        for docs in documents:
            if num_doc == docs['number']:
                print(f'Владелец документа: {docs["name"]}')
                break
        else:
            print('Документ не найден в базе')
    else:
        print('Неверная команда')


Введите команду: 
k
Неверная команда
Введите команду: 
p
Введите номер документа: 
1002
Документ не найден в базе
Введите команду: 
p
Введите номер документа: 
10006
Владелец документа: Аристарх Павлов
Введите команду: 
q
Всего хорошего


In [9]:
def owner_by_document (num_doc):
  """
  Функция для поиска документа в списке documents
  Осуществляет поиск вводимого пользователем значения и при успешном совпадении вывод владельца документа
  """
  for docs in documents:
    if num_doc == docs['number']:
      return(f'Владелец документа: {docs["name"]}')
  return(f'Документ не найден в базе')

In [10]:
num_doc = input('Введите номер документа: \n')

owner_by_document (num_doc)

Введите номер документа: 
11-2


'Владелец документа: Геннадий Покемонов'

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

In [11]:
# если просто поиск полки
while True:
    order = input('Введите команду: \n').lower()
    if order == 'q':
        print('Всего хорошего')
        break
    elif order == 's':
        num_doc = input('Введите номер документа: \n')
        for shelf, docs in directories.items():
            if num_doc in docs:
                print(f'Документ хранится на полке: {shelf}')
                break
        else:
            print('Документ не найден в базе')
    else:
        print('Неверная команда')

Введите команду: 
p
Неверная команда
Введите команду: 
s
Введите номер документа: 
11-2
Документ хранится на полке: 1
Введите команду: 
s
Введите номер документа: 
1002
Документ не найден в базе
Введите команду: 
q
Всего хорошего


In [12]:
def shelf_by_document(num_doc):
  """
  Функция для поиска документа в словаре directories
  Осуществляет поиск вводимого пользователем значения и при успешном совпадении вывод соответствующего ключа словаря
  """
  for shelf, docs in directories.items():
      if num_doc in docs:
          return(f'полка хранения: {shelf}')
  return('Документ не найден в базе')

In [13]:
num_doc = input('Введите номер документа: \n')
shelf_by_document (num_doc)

Введите номер документа: 
10006


'полка хранения: 2'

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```


In [14]:
# если просто вывод информации
while True:
    order = input('Введите команду: \n').lower()
    if order == 'q':
        print('Всего хорошего')
        break
    elif order == 'l':
        for docs in documents:
            print(f'№ {docs["number"]}, тип: {docs["type"]}, владелец: {docs["name"]}, {shelf_by_document(docs["number"])}')  # используем созданную ранее функцию для поиска по словарю
    else:
        print('Неверная команда')

Введите команду: 
о
Неверная команда
Введите команду: 
д
Неверная команда
Введите команду: 
l
№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Введите команду: 
q
Всего хорошего


In [15]:
def full_info():
  """
  Функция для вывода полной информации о документах: проходит по всем значениям списка словарей documents и словаря directories
  """
  for docs in documents:
    print(f'№ {docs["number"]}, тип: {docs["type"]}, владелец: {docs["name"]}, {shelf_by_document(docs["number"])}')

In [16]:
full_info()

№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

In [17]:
# если просто отработка по команде ads с проверкой команды
while True:
    order = input('Введите команду: \n').lower()
    if order == 'q':
        print('Всего хорошего')
        break
    elif order == 'ads':
        new_num_shelf = input('Введите номер полки: \n')
        if new_num_shelf not in directories:
                directories[new_num_shelf] = []
                print (f'Полка добавлена. Текущий перечень полок: {" ".join(list(directories))}')
        else:
                print(f'Такая полка уже существует. Текущий перечень полок: {" ".join(list(directories))}')
    else:
        print('Неверная команда')

Введите команду: 
h
Неверная команда
Введите команду: 
asd
Неверная команда
Введите команду: 
ads
Введите номер полки: 
5
Полка добавлена. Текущий перечень полок: 1 2 3 5
Введите команду: 
s
Неверная команда
Введите команду: 
ads
Введите номер полки: 
1
Такая полка уже существует. Текущий перечень полок: 1 2 3 5
Введите команду: 
q
Всего хорошего


In [18]:
def add_shelf(new_num_shelf):
    """
    Функция для добавления новой полки - нового ключа с пустым значением в словарь directories
    """
    if new_num_shelf not in directories:
        directories[new_num_shelf] = []
        return(f'Полка добавлена. Текущий перечень полок: {" ".join(list(directories))}')
    return(f'Такая полка уже существует. Текущий перечень полок: {" ".join(list(directories))}')

In [19]:
new_num_shelf = input('Введите номер полки: \n')
add_shelf (new_num_shelf)

Введите номер полки: 
5


'Такая полка уже существует. Текущий перечень полок: 1 2 3 5'

### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

In [21]:
# если просто отработка по команде ds с проверкой команды
while True:
    order = input('Введите команду: \n').lower()
    if order == 'q':
        print('Всего хорошего')
        break
    elif order == 'ds':
        num_shelf = input('Введите номер полки: \n')
        if num_shelf not in directories:
            print (f'Такой полки не существует. Текущий перечень полок: {" ".join(list(directories))}')
        else:
            if directories[num_shelf] != []:
                print(f'На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: {" ".join(list(directories))}')
            else:
                del directories[num_shelf]
                print(f'Полка удалена. Текущий перечень полок: {" ".join(list(directories))}')
    else:
        print('Неверная команда')

Введите команду: 
k
Неверная команда
Введите команду: 
ds
Введите номер полки: 
10
Такой полки не существует. Текущий перечень полок: 1 2 3 5
Введите команду: 
ds
Введите номер полки: 
5
Полка удалена. Текущий перечень полок: 1 2 3
Введите команду: 
ds
Введите номер полки: 
1
На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: 1 2 3
Введите команду: 
q
Всего хорошего


In [22]:
def del_shelf(num_shelf):
    """
    Функция для удаления полки  если она пустая - проверка на наличие ключа в словаре directories и не пустого знаяения по данному ключу
    """
    if num_shelf  in directories:
      if directories[num_shelf] != []:
         return(f'На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: {" ".join(list(directories))}')
      else:
         del directories[num_shelf]
         return(f'Полка удалена. Текущий перечень полок: {" ".join(list(directories))}')
    return(f'Такой полки не существует. Текущий перечень полок: {" ".join(list(directories))}')
        

In [24]:
num_shelf = input('Введите номер полки: \n')
del_shelf(num_shelf)

Введите номер полки: 
1


'На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: 1 2 3'

## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [48]:
# если просто отработка по команде ad с проверкой команды
while True:
    order = input('Введите команду: \n').lower()
    if order == 'q':
        print('Всего хорошего')
        break
    elif order == 'ad':
        new_num_doc = input('Введите номер документа: \n')
        if new_num_doc in [doc for doc_list in [values for values in directories.values()] for doc in doc_list]:
            print(f'такой документ уже существует')
        else:
            new_type_doc = input('Введите тип документа: \n')
            new_owner_doc = input('Введите владельца документа: \n')
            num_shelf = input('Введите полку для хранения: \n')
            
            if num_shelf not in directories:
                print (f'Такой полки не существует. Добавьте полку командой as.')
                print (f'Текущий список документов:')
                full_info()
            else:
                directories[num_shelf] += [new_num_doc]
                documents.append({'type': new_type_doc, 'number': new_num_doc, 'name': new_owner_doc})
                print(f'Документ добавлен. Текущий список документов:')
                full_info()
    else:
        print('Неверная команда')

Введите команду: 
ad
Введите номер документа: 
456
такой документ уже существует
Введите команду: 
ad
Введите номер документа: 
789
Введите тип документа: 
instruction
Введите владельца документа: 
C3PO
Введите полку для хранения: 
2
Документ добавлен. Текущий список документов:
№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№ 456, тип: multy, владелец: r2d2, полка хранения: 3
№ 789, тип: instruction, владелец: C3PO, полка хранения: 2
Введите команду: 
q
Всего хорошего


In [66]:
def add_docs(new_num_doc):
    """
    Функция для добавления нового документа - осуществляется проверка на наличие документа и на возможность  положить его в хранилище
    """
    if new_num_doc not in [doc for doc_list in [values for values in directories.values()] for doc in doc_list]:
        new_type_doc = input('Введите тип документа: \n')
        new_owner_doc = input('Введите владельца документа: \n')
        num_shelf = input('Введите полку для хранения: \n')
            
        if num_shelf not in directories:
            return print(f'Такой полки не существует. Добавьте полку командой as. \nТекущий список документов: '), full_info()
        directories[num_shelf] += [new_num_doc]
        documents.append({'type': new_type_doc, 'number': new_num_doc, 'name': new_owner_doc})
        return print(f'Документ добавлен. Текущий список документов:'), full_info()

    return print(f'Такой документ уже существует. Текущий список документов:'),full_info()

In [65]:
new_num_doc = input('Введите номер документа: \n')
add_docs (new_num_doc)

Введите номер документа: 
4785
Введите тип документа: 
ghk
Введите владельца документа: 
гне
Введите полку для хранения: 
5
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов: 
№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№ 456, тип: multy, владелец: r2d2, полка хранения: 3
№ 789, тип: instruction, владелец: C3PO, полка хранения: 2


(None, None)

In [46]:
full_info()

№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№ 456, тип: multy, владелец: r2d2, полка хранения: 3



### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```


In [71]:
def del_docs(num_doc):
    """
    Функция для удаления документа - осуществляется проверка на наличие документа и удаление его в списке documents и словаре directories
    """
    for shelf, docs in directories.items():
        if num_doc in docs:
           docs.remove(num_doc)
    for doc in documents:
        if num_doc == doc['number']:
          documents.remove(doc)
          return print(f'Документ удален. \nТекущий список документов: '), full_info()

    return print(f'Документ не найден в базе. \nТекущий список документов:'),full_info()

In [73]:
num_doc = input('Введите номер документа: \n')
del_docs (num_doc)

Введите номер документа: 
11-2
Документ удален. 
Текущий список документов: 
№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№ 456, тип: multy, владелец: r2d2, полка хранения: 3
№ 789, тип: instruction, владелец: C3PO, полка хранения: 2


(None, None)



### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [112]:
def move_docs(num_doc, num_shelf):
    """
    Функция для перемещения документа в хранилище- осуществляется проверка на наличие документа в значениях словаря directories  и полки(ключа в данном словаре) и перемещение
    """
    if num_shelf not in directories:
        return (f'Такой полки не существует. Текущий перечень полок: {" ".join(list(directories))} ')

    for shelf, docs in directories.items():
        if num_doc in docs:
            docs.remove(num_doc)
            directories[num_shelf] += [num_doc]
            return print(f'Документ перемещен. \nТекущий список документов: '), full_info()
            return print(f'Документ не найден в базе. \nТекущий список документов:'), full_info()

In [114]:
num_doc = input('Введите номер документа, который хотите переместить: \n')
num_shelf = input("Введите номер полки на которую хотите переместить документ: ")
move_docs (num_doc, num_shelf)

Введите номер документа, который хотите переместить: 
456
Введите номер полки на которую хотите переместить документ: 3
456 3 3
Документ перемещен. 
Текущий список документов: 
№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№ 456, тип: multy, владелец: r2d2, полка хранения: 3
№ 789, тип: instruction, владелец: C3PO, полка хранения: 2


(None, None)

In [115]:
from pprint import pprint
pprint(documents)
pprint(directories)

[{'name': 'Василий Гупкин', 'number': '2207 876234', 'type': 'passport'},
 {'name': 'Аристарх Павлов', 'number': '10006', 'type': 'insurance'},
 {'name': 'r2d2', 'number': '456', 'type': 'multy'},
 {'name': 'C3PO', 'number': '789', 'type': 'instruction'}]
{'1': ['2207 876234'], '2': ['10006', '789'], '3': ['456']}


In [139]:
# реализуем главную функцию
def main(instruction):
    if instruction == 'p':
        num_doc = input('Введите номер документа: \n')
        print(owner_by_document (num_doc))
    elif instruction == 'l':
        full_info()
    elif instruction == 's':
        num_doc = input('Введите номер документа, чтобы узнать на какой он полке: \n')
        print(shelf_by_document (num_doc))
    elif instruction == 'ads':
        new_num_shelf = input('Введите номер полки, которую хотите добавить: \n')
        print(add_shelf(new_num_shelf))
    elif instruction == 'ds':
        num_shelf = input('Введите номер полки, которую хотите удалить: \n')
        print(del_shelf(num_shelf))
    elif instruction == 'ad':
        new_num_doc = input('Введите номер документа, который хотите добавить: \n')
        add_docs (new_num_doc)
    elif instruction == 'd':
        num_doc = input('Введите номер документа? который хотите удалить: \n')
        del_docs (num_doc)
    elif instruction == 'm':
        num_doc = input('Введите номер документа, который хотите переместить: \n')
        num_shelf = input("Введите номер полки на которую хотите переместить документ: ")
        move_docs(num_doc, num_shelf)        
    else:
        print('Введена не верная команда.')

In [ ]:
while True:
    instruction = input ('\nВведите команду: ').lower()
    if instruction == 'q':
        complete_info()
        break
    else:
        main(instruction)


Введите команду: ь
Введена не верная команда.

Введите команду: m
Введите номер документа, который хотите переместить: 
236
Введите номер полки на которую хотите переместить документ: 1
Документ перемещен. 
Текущий список документов: 
№ 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№ 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№ 456, тип: multy, владелец: r2d2, полка хранения: 3
№ 789, тип: instruction, владелец: C3PO, полка хранения: 2
№ 236, тип: lime, владелец: limon, полка хранения: 1


#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой [Google Colab](https://colab.research.google.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.